apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: disparar-github-action
  title: Ejecutar Workflow de GitHub
  annotations:
    backstage.io/techdocs-ref: value
spec:
  owner: user:default/guest
  type: service

  parameters:
    - title: Datos del Repositorio
      properties:
        repoUrl:
          title: URL del Repositorio
          type: string
          ui:field: RepoUrlPicker # Esto muestra un selector de tus repos
          ui:options:
            allowedHosts:
              - github.com # <--- Esto fuerza a que aparezca en la lista

  steps:
    - id: github-action
      name: Disparando Workflow
      action: github:actions:dispatch
      input:
        repoUrl: ${{ parameters.repoUrl }}
        workflowId: 'workflow.yml' # Nombre del archivo .yml en tu repo
        branchOrTagName: 'main'
        workflowInputs:
          message: 'Ejecutado desde Backstage'
