name: Accion disparada desde Backstage

# El trigger 'workflow_dispatch' es obligatorio para que Backstage lo vea
on:
  workflow_dispatch:
    inputs:
      nombre_proyecto:
        description: 'Nombre del proyecto creado en Backstage'
        required: true
        default: 'Proyecto-Generico'
      mensaje_personalizado:
        description: 'Un mensaje descriptivo'
        required: false
        default: 'Ejecución manual desde Scaffolder'

jobs:
  backstage-task:
    name: Tarea de Automatizacion
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Mostrar datos recibidos
        run: |
          echo "Iniciando proceso para: ${{ github.event.inputs.nombre_proyecto }}"
          echo "Mensaje recibido: ${{ github.event.inputs.mensaje_personalizado }}"
          echo "Ejecutado por el actor: ${{ github.actor }}"

      - name: Ejemplo de paso adicional
        run: |
          echo "Aquí podrías ejecutar scripts, despliegues o validaciones."
          date
